version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt

linters-settings:
  misspell:
    locale: US
